version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          key: 'mix-deps-pretest-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}'
      - run: mix local.hex --force && mix local.rebar --force
      - run: mix deps.get
      - save_cache:
          paths: ['deps']
          key: 'mix-deps-pretest-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}'
      - restore_cache:
          key: 'mix-build-posttest-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}'

      - run: mix compile --force --warnings-as-errors
      - run: mix test
      - run: mix credo --strict
      - run: mix dialyzer --halt-exit-status

      - save_cache:
          paths: ['_build']
          key: 'mix-build-posttest'
